feat: Make pipeline required
meroxa/terraform-provider-meroxa pull request #14
Opened 2021-09-09 10:44 UTC by raulb

https://github.com/meroxa/platform-api/pull/560

Part of https://github.com/meroxa/product/pull/128

2021-09-09 11:00 UTC, raulb commented
@terrancej I'm not sure what's the best way to test this and also why these acceptance tests are failing. Any guidance?

2021-09-09 15:37 UTC, terrancej requested changes
exactly oneof needs to name of the keys on only of the keys I put in suggestions. Add a test that adds both ensure it fails, add a test that adds none ensure it fails and then maybe a test for both individually

2021-09-09 15:37 UTC, terrancej commented on meroxa/resource_connector.go
> +				ExactlyOneOf: []string{"pipeline_name"},
```suggestion
				ExactlyOneOf: []string{"pipeline_name", "pipeline_id"},
```

2021-09-09 15:37 UTC, terrancej commented on meroxa/resource_connector.go
> +				ExactlyOneOf: []string{"pipeline_id"},
```suggestion
```

2021-09-10 15:01 UTC, terrancej approved these changes
LGTM

2021-09-10 15:02 UTC, merged